#!/usr/bin/env bash

base_dir=$(dirname "$0")
ARGS=
if [ -f "./gdbinit" ]; then
	ARGS=$ARGS\ -x\ ./gdbinit
fi

if [ -z "$TMUX" ]
then
    exec_cmd="exec tmux new -n GDB"
else
    exec_cmd="exec tmux new-window -n GDB"
fi


# 27-09-2023 02:45 Agregado para usar .tgdbinit en directorio actual en caso de existir.
# Usado para cuando se debuguea con docker y configura conecxion desde el tgdbinit

if [ -f .tgdbinit ]
then
    tgdbinit_path='.tgdbinit'
else
    tgdbinit_path='~/.tgdbinit'
fi

$exec_cmd sh -c "gdb -x $tgdbinit_path $ARGS ${@@Q} ; tmux kill-window -t \$TMUX_PANE"


